console.log(typeof 42); // Output: "number"
console.log(typeof "Hello"); // Output: "string"
console.log(typeof true); // Output: "boolean"
console.log(typeof null); // Output: "object" 
console.log(typeof undefined); // Output: "undefined"
console.log(typeof {}); // Output: "object"
console.log(typeof []); // Output: "object"
